services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=smis
      - DB_USERNAME=root
      - DB_PASSWORD=password

  mariadb:
    image: mariadb:10.5
    container_name: laravel-mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: smis
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
